general.import = ["/home/joao/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = -2

[colors.primary]
background = '#111111'

[scrolling]
history = 5000

[window]
decorations = "none"
dynamic_padding = false
opacity = 1
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 8
