# TODO: Finish migrating colors to custom poimandres theme
# - #fffac2
# - #5de4c7
# - #5fb3a1
# - #42675a
# - #89ddff
# - #add7ff
# - #91b4d5
# - #7390aa
# - #d0679d
# - #f087bd
# - #a6accd
# - #767c9d
# - #506477
# - #303340
# - #1b1e28
# - #e4f0fb
# - #1b212e
# - #ffffff

[manager]
cwd = { fg = "#e4f0fb" }

hovered         = { fg = "#5de4c7", bg = "#303340" }
preview_hovered = { underline = false }
find_keyword  = { fg = "#f9e2af", italic = true }
find_position = { fg = "#f5c2e7", bg = "reset", italic = true }
marker_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }
marker_selected = { fg = "#1b212e", bg = "#5de4c7" }
tab_active   = { fg = "#1e1e2e", bg = "#cdd6f4" }
tab_inactive = { fg = "#cdd6f4", bg = "#45475a" }
tab_width    = 1
count_copied   = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut      = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#89b4fa" }
border_symbol = "│"
border_style  = { fg = "#303340" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#45475a", bg = "#45475a" }

mode_normal = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
mode_select = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
mode_unset  = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#89b4fa", bg = "#45475a" }
progress_error  = { fg = "#f38ba8", bg = "#45475a" }

permissions_t = { fg = "#89b4fa" }
permissions_r = { fg = "#f9e2af" }
permissions_w = { fg = "#f38ba8" }
permissions_x = { fg = "#a6e3a1" }
permissions_s = { fg = "#7f849c" }

[input]
border   = { fg = "#89b4fa" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#89b4fa" }
active   = { fg = "#f5c2e7" }
inactive = {}

[tasks]
border  = { fg = "#89b4fa" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#313244" }
cand            = { fg = "#94e2d5" }
rest            = { fg = "#9399b2" }
desc            = { fg = "#f5c2e7" }
separator       = "  "
separator_style = { fg = "#585b70" }

[help]
on      = { fg = "#f5c2e7" }
exec    = { fg = "#94e2d5" }
desc    = { fg = "#9399b2" }
hovered = { bg = "#585b70", bold = true }
footer  = { fg = "#45475a", bg = "#cdd6f4" }

[filetype]
rules = [
	{ mime = "image/*", fg = "#fffac2" },
	{ mime = "video/*", fg = "#fffac2" },
	{ mime = "audio/*", fg = "#fffac2" },

	{ mime = "application/zip",             fg = "#d0679d" },
	{ mime = "application/gzip",            fg = "#d0679d" },
	{ mime = "application/x-tar",           fg = "#d0679d" },
	{ mime = "application/x-bzip",          fg = "#d0679d" },
	{ mime = "application/x-bzip2",         fg = "#d0679d" },
	{ mime = "application/x-7z-compressed", fg = "#d0679d" },
	{ mime = "application/x-rar",           fg = "#d0679d" },

	{ name = "*", fg = "#e4f0fb" },
	{ name = "*/", fg = "#ffffff" }
]
