-- Extra autostart processes.
hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm-app -- mako")
    hl.exec_cmd("uwsm-app -- fcitx5 --disable notificationitem")
    hl.exec_cmd("uwsm-app -- swaybg -i ~/.config/omarchy/current/background -m fill")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("omarchy-cmd-first-run")
    hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("uwsm app -- walker --gapplication-service")
    hl.exec_cmd("numlockx on")
    hl.exec_cmd("quickshell")
end)
