source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

windowrule = tag -firefox-based-browser, match:initial_class (zen)
windowrule = float on, match:initial_class zen
windowrule = size 500 800, match:initial_class zen
windowrule = center on, match:initial_class zen

windowrule = float on, match:class chrome-chatgpt.com__-Default
windowrule = size 600 800, match:class chrome-chatgpt.com__-Default
windowrule = move 1947 47,  match:class chrome-chatgpt.com__-Default

windowrule = float on, match:class chrome-translate.google.pt__-Default
windowrule = size 600 800, match:class chrome-translate.google.pt__-Default
windowrule = move 1343 47,  match:class chrome-translate.google.pt__-Default

windowrule = render_unfocused on, match:initial_class steam_app_230410

windowrule = float on, match:initial_class Aether
windowrule = size 1259 1000, match:initial_class Aether
windowrule = center on, match:initial_class Aether
