# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 7
    gaps_out = 10
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 4
}
