# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 7
    gaps_out = 10
}

decoration {
    rounding = 4

    blur {
        enabled = true
        size = 5
        passes = 2
    }
}

layerrule = blur on, match:namespace superbar
layerrule = no_anim on, match:namespace superbar
