force_keyboard_focus = true
close_when_open = true
selection_wrap = false
global_argument_delimiter = "#" # query: firefox#https://benz.dev => part after delimiter will be ignored when querying. this should be the same as in the elephant config
keep_open_modifier = "shift" # won't close on activation, but rather select the next item in the list
exact_search_prefix = "'" # disable fuzzy searching
theme = "joao"
disable_mouse = false
additional_theme_location = "~/.config.jmmm.sh/dotfiles/walker/themes/"

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Start", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = "Escape"
next = "ctrl n"
previous = "ctrl p"
toggle_exact = "ctrl e"
resume_last_query = "ctrl r"
quick_activate = ["alt 1", "alt 2", "alt 3", "alt 4", "alt 5", "alt 6", "alt 7", "alt 8", "alt 9"]

[list]
max_entries = 200
cycle = true

[providers]
default = [
	"desktopapplications",
	"menus",
	"websearch",
]
empty = ["desktopapplications"]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = "*"
provider = "symbols"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[providers.calc]
default = "copy"
copy = "Return"
save = "ctrl s"
delete = "ctrl d"

[providers.clipboard]
time_format = "%d.%m. - %H:%M"
default = "copy"
copy = "Return"
delete = "ctrl d"
edit = "ctrl o"
toggle_images_only = "ctrl i"
