#!/usr/bin/env bash
set -euo pipefail

FORCE_DELETE=false
CONFIG="$HOME/.config.jmmm.sh"

if [[ ${OS:-} = Windows_NT ]]; then
	echo '[ERROR] This config is destined for linux systems.'
	exit 1
fi

while [[ $# -gt 0 ]]; do
	case "$1" in
	--force | -f)
		FORCE_DELETE=true
		;;
	*)
		echo "Unknown option: $1"
		exit 1
		;;
	esac
	shift
done

path() {
	local new_path="$1"

	if [[ ":$PATH:" != *":$new_path:"* ]]; then
		export PATH="$new_path:$PATH"
		echo "[SUCCESS] Added $new_path to PATH"
	else
		echo "[INFO] Path $new_path already exists in PATH"
	fi
}

symlink() {
	local config_path="$1"
	local source_path="$2"

	if [ ! -t 0 ]; then
		if [ -e "$config_path" ]; then
			echo "[INFO] Creating backup of existing config at $config_path.bak..."
			mv "$config_path" "$config_path.bak"
		fi

		ln -s "$source_path" "$config_path"
		echo "[SUCCESS] Symlink created successfully: $source_path -> $config_path"

		return
	fi

	if [[ "$FORCE_DELETE" == true || ! -e "$config_path" ]]; then
		rm -rf "$config_path"
		ln -s "$source_path" "$config_path"
		echo "[SUCCESS] Symlink created successfully: $source_path -> $config_path"

		return
	fi

	echo "[ERROR] There's already a config in $config_path"
	echo "[INFO] You can:"
	echo "[INFO] 1. Delete it [D]"
	echo "[INFO] 2. Backup it and proceed with symlinking [B] (default)"
	echo "[INFO] 3. Don't symlink this config [N]"

	read -n1 -p "Enter your choice [D/B/N]: " response
	echo ""

	case $response in
	[dD])
		echo "[INFO] Deleting existing config at $config_path..."
		rm -rf "$config_path"
		ln -s "$source_path" "$config_path"
		echo "[SUCCESS] Symlink created successfully: $source_path -> $config_path"
		;;
	[bB] | "")
		echo "[INFO] Creating backup of existing config at $config_path.bak..."
		mv "$config_path" "$config_path.bak"
		ln -s "$source_path" "$config_path"
		echo "[SUCCESS] Symlink created successfully: $source_path -> $config_path. Previous config backed up as $config_path.bak"
		;;
	[nN])
		echo "[INFO] Symlinking for $source_path cancelled."
		;;
	*)
		echo "[INFO] Invalid choice."
		symlink "$config_path" "$source_path"
		;;
	esac
}

echo "Creating symlinks for config files...\n"

symlink "$HOME/.config/nvim" "$CONFIG/dotfiles/nvim"
symlink "$HOME/.config/starship.toml" "$CONFIG/dotfiles/starship/starship.toml"
symlink "$HOME/.config/alacritty" "$CONFIG/dotfiles/alacritty"
symlink "$HOME/.config/vicinae" "$CONFIG/dotfiles/vicinae"
symlink "$HOME/.config/yazi" "$CONFIG/dotfiles/yazi"
symlink "$HOME/.config/tmux" "$CONFIG/dotfiles/tmux"
symlink "$HOME/.config/hypr" "$CONFIG/dotfiles/hypr"
symlink "$HOME/.config/quickshell" "$CONFIG/dotfiles/quickshell"
symlink "$HOME/.config/ghostty" "$CONFIG/dotfiles/ghostty"
symlink "$HOME/.config/lazygit" "$CONFIG/dotfiles/lazygit"
symlink "$HOME/.config/systemd" "$CONFIG/dotfiles/systemd"
symlink "$HOME/.config/atuin" "$CONFIG/dotfiles/atuin"
symlink "$HOME/.config/ramo" "$CONFIG/dotfiles/ramo"
symlink "$HOME/.config/voxtype" "$CONFIG/dotfiles/voxtype"
symlink "$HOME/.config/opencode" "$CONFIG/dotfiles/opencode"
symlink "$HOME/.config/tuicr" "$CONFIG/dotfiles/tuicr"
symlink "$HOME/.config/hyprwhspr/config.json" "$CONFIG/dotfiles/hyprwhspr/config.json"
symlink "$HOME/.gitconfig" "$CONFIG/dotfiles/git/.gitconfig"
symlink "$HOME/.bashrc" "$CONFIG/dotfiles/bash/.bashrc"
symlink "$HOME/biome.json" "$CONFIG/dotfiles/biome/config.json"
symlink "$HOME/.local/bin/toggle-sink" "$CONFIG/bin/toggle-sink"

echo "Setup complete!"
