#!/usr/bin/env bash

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias c='clear'
alias t='tmux'
alias r='reset'
alias fd='fdfind'
alias gg='lazygit'
alias lzd='lazydocker'
alias lab='cd ~/lab'
alias config='cd ~/.config.jmmm.sh'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias bfg='java -jar ~/bin/bfg.jar'
alias nv='nvim'
alias nvl='nvim leet'
alias yt-dlp-mp4='yt-dlp -S res,ext:mp4:m4a --recode mp4'
alias oc='opencode'

if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi
