#!/usr/bin/env bash

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

shopt -s histappend
shopt -s checkwinsize
set -o vi
bind 'set completion-ignore-case on'

source "$BASH_CONFIG_DIR/alias"
source "$BASH_CONFIG_DIR/functions"
source "$BASH_CONFIG_DIR/extensions/zoxide"
source "$BASH_CONFIG_DIR/extensions/atuin"
source "$BASH_CONFIG_DIR/extensions/starship"
source "$BASH_CONFIG_DIR/extensions/pyenv"

export XDG_CONFIG_HOME="$HOME/.config"
export BUN_INSTALL="$HOME/.bun"
export NVM_DIR="$HOME/.nvm"
export PNPM_HOME="$HOME/.local/share/pnpm"
export EDITOR='nvim'
export VISUAL='nvim'
export NVIM_AI=true
export NVIM_THEME=kanagawa-paper

[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
[ -f "$BASH_CONFIG_DIR/.env" ] && export $(grep -v '^[[:space:]]*#' "$BASH_CONFIG_DIR/.env" | xargs -0)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

add_to_path "$HOME/go/bin"
add_to_path "$HOME/.opencode/bin"
add_to_path "$HOME/.local/share/solana/install/active_release/bin"
add_to_path "$HOME/.config.jmmm.sh/bin"
add_to_path "$HOME/.local/bin"
add_to_path "$HOME/bin"
add_to_path "$BUN_INSTALL/bin"
add_to_path $PNPM_HOME
add_to_path "/opt/nvim-linux64/bin"
add_to_path "/mnt/c/Users/joao/AppData/Local/Programs/cursor/resources/app/bin"
