#!/usr/bin/env bash

function gi() {
    curl -sL "https://www.toptal.com/developers/gitignore/api/$@"
}

function add_to_path() {
    if [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH="$1:$PATH"
    fi
}

function t() {
    if tmux has-session 2>/dev/null; then
        tmux attach
    else
        tmux new-session -s lab -c ~/lab
    fi
}
